name: checkout files and folders
on: push
jobs:
  checkout-actions:
    runs-on: ubuntu-latest
    steps:
      - name: list files before
        run: ls -a
      - name: checkout actions
        uses: actions/checkout@v3
      - name: list files after
        uses: ls -a
  checkout-actions-manually
    runs-on: ubuntu-latest
    steps:
      - name: list files before
        run: ls -a
      - name: checkout
        run: |
          git init
          git remote add origin "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git"
          git fetch origin
          git checkout main
      - name: list files after
        run: ls -a
