name: concurrency02
run-name: concurrency-2
on:
    workflow_dispatch:
        inputs:
            environment:
                description: the environment in which this job runs
                required: true
                type: environment
concurrency:
    group: ${{github.workflow}}-${{github.event.inputs.environment}}
    # cancel-in-progess: true
jobs:
    concurrency-2:
        runs-on: ubuntu-latest
        steps:
            - name: concurrency-2
              run: sleep 20
