name: Expression and context
on: push
run-name: Expression and contexts are created by @${{GITHUB.actor}}
jobs:
    Expressions:
    runs-on: ubuntu-latest
    steps:
    - name: expression representation
      run: |
      echo ${{1}}
      echo ${{'this is string'}}
      echo ${{ 1 > 2 }}
      echo ${{ 'string' == 'STRING'}}
      echo ${{ true && false}}

    