name: forking a repository
on: push
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
    - name: just an echo
      run: echo "hi i am going great"
    - name: printing actions
      run: ${{ GITHUB.EVENTS }}
