name: working directories and shell
on: push
defaults:
  run:
    shell: bash
jobs:
  running-ubuntu-machine:
    runs-on: ubuntu-latest
    steps:
    - name: Display working directory and contents
      run: |
        pwd
        ls -a
        echo $GITHUB_SHA
        echo $GITHUB_REPOSITORY
        echo $GITHUB_WORKSPACE
    